before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/aws-auth/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    ldflags: -buildid="" -s -w

archives:
  - format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Version }}-{{ .ShortCommit }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  prerelease: auto

brews:
  - github:
      owner: telia-oss
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/telia-oss/aws-auth
    description: CLI for authenticating against AWS
    test: |
      system "#{bin}/aws-auth --version"
