before:
  hooks:
    - go mod download

builds:
- main: ./cmd/gotemplate/main.go
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
  ldflags: -buildid="" -s -w

archives:
  - format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Version }}-{{ .ShortCommit }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  prerelease: auto

brews:
  - github:
      owner: itsdalmo
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/itsdalmo/gotemplate
    description: Template for go project and tap.
    test: |
      system "#{bin}/gotemplate --version"
